Try this on full spam.csv file and bigram matching instead of unigram matching

Spam classification using Count Vectorization and TFIDf Vectorization

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
stopwords = ["a", "about", "above", "after", "again", "against", "all", "am",
"an", "and", "any", "are", "as", "at", "be", "because", "been", "before",
"being", "below", "between", "both", "but", "by", "could", "did", "do",
"does", "doing", "down", "during", "each", "few", "for", "from", "further",
"had", "has", "have", "having", "he", "he'd", "he'll", "he's", "her", "here",
"here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i",
"i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "it", "it's", "its",
"itself", "let's", "me", "more", "most", "my", "myself", "nor", "of", "on",
"once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out",
"over", "own", "same", "she", "she'd", "she'll", "she's", "should", "so",
"some", "such", "than", "that", "that's", "the", "their", "theirs", "them",
"themselves", "then", "there", "there's", "these", "they", "they'd",
"they'll", "they're", "they've", "this", "those", "through", "to", "too",
"under", "until", "up", "very", "was", "we", "we'd", "we'll", "we're",
"we've", "were", "what", "what's", "when", "when's", "where", "where's",
"which", "while", "who", "who's", "whom", "why", "why's", "with", "would",
"you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
"yourselves"]

In [5]:
from sklearn import preprocessing
import numpy as np
datasets = pd.read_csv('/content/drive/MyDrive/ML/spam.csv', encoding="ISO-8859-1")
datasets.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis = 1, inplace = True)
datasets["v1"]=np.where(datasets["v1"]=='spam',1,0)
print("\nData :\n",datasets.head(20))


Data :
     v1                                                 v2
0    0  Go until jurong point, crazy.. Available only ...
1    0                      Ok lar... Joking wif u oni...
2    1  Free entry in 2 a wkly comp to win FA Cup fina...
3    0  U dun say so early hor... U c already then say...
4    0  Nah I don't think he goes to usf, he lives aro...
5    1  FreeMsg Hey there darling it's been 3 week's n...
6    0  Even my brother is not like to speak with me. ...
7    0  As per your request 'Melle Melle (Oru Minnamin...
8    1  WINNER!! As a valued network customer you have...
9    1  Had your mobile 11 months or more? U R entitle...
10   0  I'm gonna be home soon and i don't want to tal...
11   1  SIX chances to win CASH! From 100 to 20,000 po...
12   1  URGENT! You have won a 1 week FREE membership ...
13   0  I've been searching for the right words to tha...
14   0                I HAVE A DATE ON SUNDAY WITH WILL!!
15   1  XXXMobileMovieClub: To use your credit, click ...
16   

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(datasets["v2"], datasets["v1"],random_state=77)
X_test.shape

(1393,)

CountVectorizer


Perform count vectorization on training data.

In [7]:
vectorizer = CountVectorizer(ngram_range = (2, 2),stop_words=stopwords)
vectorizer.fit(X_train)
X_train_vectorized = vectorizer.fit_transform(X_train)
# print(vectorizer.get_feature_names())
print(X_train_vectorized.toarray())


/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let', 'll', 're', 've'] not in stop_words.
  % sorted(inconsistent)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model=MultinomialNB()
model.fit(X_train_vectorized,y_train)

MultinomialNB()

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
predictions = model.predict(vectorizer.transform(X_test))

print("Accuracy: ", accuracy_score(y_test, predictions))
print("\nPrecision: ", precision_score(y_test, predictions))
print("\nRecall: ", recall_score(y_test, predictions))

Accuracy:  0.9777458722182341

Precision:  1.0

Recall:  0.8287292817679558


Apply the Decision Tree Classifier on vectorized data.

In [10]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train_vectorized, y_train)

DecisionTreeClassifier()

In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
predictions = clf.predict(vectorizer.transform(X_test))

print("Accuracy: ", accuracy_score(y_test, predictions))
print("\nPrecision: ", precision_score(y_test, predictions))
print("\nRecall: ", recall_score(y_test, predictions))

Accuracy:  0.9605168700646087

Precision:  0.9846153846153847

Recall:  0.7071823204419889


TFIDF Vectorizer


Perform IFIDF vectorization on training data.

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(ngram_range = (2, 2),stop_words = stopwords)
vectorizer.fit(X_train)
X_train_tfidf_vectorized = vectorizer.transform(X_train)
print(X_train_tfidf_vectorized.toarray())

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:401: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['let', 'll', 're', 've'] not in stop_words.
  % sorted(inconsistent)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]



Apply the Naive Bayes on IFIDF vectorized data.

In [13]:
model = MultinomialNB()
model.fit(X_train_tfidf_vectorized, y_train)

MultinomialNB()

In [14]:
predictions = model.predict(vectorizer.transform(X_test))

print("Accuracy: ", accuracy_score(y_test, predictions))
print("\nPrecision: ", precision_score(y_test, predictions))
print("\nRecall: ", recall_score(y_test, predictions))

Accuracy:  0.9418521177315147

Precision:  1.0

Recall:  0.5524861878453039


Apply the Decision Tree Classifier on IFIDF vectorized data.

In [15]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train_tfidf_vectorized, y_train)

DecisionTreeClassifier()

In [16]:
predictions = clf.predict(vectorizer.transform(X_test))

print("Accuracy: ", accuracy_score(y_test, predictions))
print("\nPrecision: ", precision_score(y_test, predictions))
print("\nRecall: ", recall_score(y_test, predictions))

Accuracy:  0.9583632447954056

Precision:  0.984251968503937

Recall:  0.6906077348066298
