1) Create a Numpy array of size 4 x 5.

In [ ]:
import numpy as np
from numpy import random
narray = np.array([[1, 2, 3, 4],[5 ,6 ,7 ,8 ],[9 ,10 ,11 ,12],[13 , 14, 15, 16,],[17 ,18, 19,20 ]])
print(narray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


2) Randomly initialize the array.

In [ ]:

print(np.random.rand(2,5))

[[0.75630845 0.39735714 0.37349564 0.08458778 0.69819149]
 [0.94533272 0.26831411 0.95306855 0.57560946 0.32083825]]


3) Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [ ]:
mat3=np.array([[1,2],[3,4]])
print("Transpose matrix:")
print(mat3.T)
print("square array:")
sqkmatrix = mat3 * mat3
print(sqkmatrix)
print("Value of determinent is:")
det=np.linalg.det(sqkmatrix)
print(int(det))


Transpose matrix:
[[1 3]
 [2 4]]
square array:
[[ 1  4]
 [ 9 16]]
Value of determinent is:
-20


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [ ]:
mat4=np.array(np.random.rand(5,4))
print(mat4)

[[0.12049464 0.38642886 0.47491442 0.56370293]
 [0.48266437 0.04946675 0.58491026 0.60267308]
 [0.60052548 0.22028842 0.26196645 0.61601309]
 [0.57612615 0.91872485 0.40904216 0.85301333]
 [0.69746614 0.59330777 0.27978891 0.86591985]]


5) Perform Matrix multiplication.

In [ ]:
mat5=np.array([[1,2],[3,4]])
mat6=np.array([[2,1],[5,7]])
print("First matrix: ")
print(mat5)
print("second matrix: ")
print(mat6)
res= np.dot(mat5,mat6)
print("Multiplication of matrix is:")
print(res)

First matrix: 
[[1 2]
 [3 4]]
second matrix: 
[[2 1]
 [5 7]]
Multiplication of matrix is:
[[12 15]
 [26 31]]


6) Perform element wise matrix multiplication.

In [ ]:
print("Multiplication element by element")
print(mat5 * mat6)

Multiplication element by element
[[ 2  2]
 [15 28]]


7) Find mean, median of the numpy array created.

In [ ]:
print("Median of array ")
print(np.median(mat5))
print("Mean of Array ")
print(np.mean(mat5))

Median of array 
2.5
Mean of Array 
2.5


8) Obtain each row in the second column of the first array.

In [ ]:
print("second column of each row is:")
print(narray[0:,1])

second column of each row is:
[ 2  6 10 14 18]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [ ]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/Iris.csv')
data2=data-np.mean(data,axis=0)
print (data2)


       Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species
0   -74.5      -2.358667     -0.998667      -0.743333         0.446     NaN
1   -73.5      -2.358667     -0.998667      -0.943333        -0.054     NaN
2   -72.5      -2.458667     -0.998667      -1.143333         0.146     NaN
3   -71.5      -2.258667     -0.998667      -1.243333         0.046     NaN
4   -70.5      -2.358667     -0.998667      -0.843333         0.546     NaN
..    ...            ...           ...            ...           ...     ...
145  70.5       1.441333      1.101333       0.856667        -0.054     NaN
146  71.5       1.241333      0.701333       0.456667        -0.554     NaN
147  72.5       1.441333      0.801333       0.656667        -0.054     NaN
148  73.5       1.641333      1.101333       0.356667         0.346     NaN
149  74.5       1.341333      0.601333       0.056667        -0.054     NaN

[150 rows x 6 columns]


10) Study about numpy array attributes and implement it on the first matrix.

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
a.shape = (3,2) 
print (a)
b = a.reshape(3,2)
print(b)
print (a.itemsize)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
8
