**Aim: Implement Linear Regression Algorithm on the given dataset.**

**Exercise 1: Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch
library). You can optionally use sklearn (if you want)**

In [ ]:
# Import Numpy & PyTorch

import torch.nn as nn
import numpy as np
import torch
from numpy.core.fromnumeric import mean

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')


# Target (apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights is: \n\t",w)

print("Bias is: \n\t",b)

Weights is: 
	 tensor([[-0.9126, -1.9460, -0.4973]], requires_grad=True)
Bias is: 
	 tensor([0.8117], requires_grad=True)


In [ ]:
#Defining the model
def model(x):
    return  torch.mm(x,w.t(),out=None)+b

In [ ]:
#Generate Predictions
pred=model(inputs)
print("Prediction is :\n",pred)

#Compare with targets
print("Target is:\n",targets)

Prediction is :
 tensor([[-217.5669],
        [-285.3007],
        [-368.1806],
        [-194.3449],
        [-283.7754]], grad_fn=<AddBackward0>)
Target is:
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# MSE loss
def MseLoss(P,T):
  sum=0
  for j in range(0,len(T)):
    sum += (T[j]-P[j])*(T[j]-P[j])
  return sum/len(T)

Loss=MseLoss(pred,targets)
print("MSE Loss is:\n",Loss)    

MSE Loss is:
 tensor([128552.0469], grad_fn=<DivBackward0>)


In [ ]:
#Computing Gradients
Loss.backward()

#Gradients for Weights
print("Gradient for Weights is:\n",w.grad)

#Gradients for Bias
print("Gradient for Bias is :\n",b.grad)

Gradient for Weights is:
 tensor([[-57777.2578, -64911.5625, -39416.8516]])
Gradient for Bias is :
 tensor([-692.0674])


In [ ]:
# Adjust weights and Bias & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
print("Gradients for weights: \n\t",w.grad)
print("Gradients for Bias:\n\t",b.grad)
print("New weights:\n\t",w)
print("New bias:\n\t",b)

Gradients for weights: 
	 tensor([[0., 0., 0.]])
Gradients for Bias:
	 tensor([0.])
New weights:
	 tensor([[-0.3348, -1.2968, -0.1031]], requires_grad=True)
New bias:
	 tensor([0.8186], requires_grad=True)


In [ ]:
#calculate new Loss
new_pred=model(inputs)
new_loss = MseLoss(new_pred, targets)
print("New Loss is:\n\t",new_loss)

New Loss is:
	 tensor([53794.7930], grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MseLoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate  new loss
preds = model(inputs)
loss = MseLoss(preds, targets)
print("Loss is:\n\t",loss)

Loss is:
	 tensor([114.8353], grad_fn=<DivBackward0>)


**Exercise 2: Try Linear regression on same prediction data using Tensorflow**

In [ ]:
#Input(Temp,Rainfall,humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target(Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights is: \n\t",w)

print("Bias is: \n\t",b)

Weights is: 
	 tensor([[1.5356, 0.9105, 0.0985]], requires_grad=True)
Bias is: 
	 tensor([0.9327], requires_grad=True)


In [ ]:
#Defining the model
def model(x):
    return  x @ w.t()+b

In [ ]:
#Generate Predictions
preds=model(inputs)
print("Prediction is :\n",preds)

#Compare with targets
print("Target is:\n",targets)

Prediction is :
 tensor([[178.2655],
        [227.0937],
        [262.2416],
        [200.3556],
        [201.1854]], grad_fn=<AddBackward0>)
Target is:
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
mseloss = nn.MSELoss()
loss = mseloss(preds, targets)
loss.backward()
print("Loss:\n\t",loss)

#Computing Gradients
print("Gradients for weights:\n\t",w.grad)
print("Gradients for Bias:\n\t",b.grad)


Loss:
	 tensor(19652.2969, grad_fn=<MseLossBackward0>)
Gradients for weights:
	 tensor([[23859.5977, 22935.0000, 14555.0254]])
Gradients for Bias:
	 tensor([275.2567])


In [ ]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mseloss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate  new loss
preds = model(inputs)
loss = mseloss(preds, targets)
print("Loss is:",loss)

Loss is: tensor(165.5763, grad_fn=<MseLossBackward0>)
