In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import tensorflow as tf

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
 # Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [ ]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.3835, -0.4371,  2.0876]], requires_grad=True)
tensor([-0.6559, -1.1639], requires_grad=True)


In [ ]:
inputs @ w.t() + b

tensor([[-41.1724, -41.6804],
        [-31.4157, -31.9236],
        [-58.5114, -59.0193],
        [-83.3313, -83.8392],
        [  8.0512,   7.5433]], grad_fn=<AddBackward0>)

In [ ]:
def model(x):
    return x @ w.t() + b
prediction=model(inputs)
print(prediction)

tensor([[-41.1724, -41.6804],
        [-31.4157, -31.9236],
        [-58.5114, -59.0193],
        [-83.3313, -83.8392],
        [  8.0512,   7.5433]], grad_fn=<AddBackward0>)


In [ ]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
# Compute loss
loss = mse(prediction, targets)
print(loss)

tensor(14799.7998, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()
# Gradients for weights
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-1.3835, -0.4371,  2.0876]], requires_grad=True)
tensor([[-20067.7344, -21577.0742, -12912.5723]])
tensor([-0.6559, -1.1639], requires_grad=True)
tensor([-117.4759, -117.9838])


In [ ]:
#before moving ahed  reset the gradients to zero
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.]])
tensor([0., 0.])


In [ ]:
# Generate predictions
preds = model(inputs)
print(preds)
# Calculate the loss
loss = mse(preds, targets)
print(loss)
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

tensor([[-41.1724, -41.6804],
        [-31.4157, -31.9236],
        [-58.5114, -59.0193],
        [-83.3313, -83.8392],
        [  8.0512,   7.5433]], grad_fn=<AddBackward0>)
tensor(14799.7998, grad_fn=<DivBackward0>)
tensor([[-20067.7344, -21577.0742, -12912.5723]])
tensor([-117.4759, -117.9838])


In [ ]:
# Calculate loss for new data
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6302.7632, grad_fn=<DivBackward0>)


In [ ]:
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)
print(preds)
print(targets)

tensor(9.3765, grad_fn=<DivBackward0>)
tensor([[ 57.0210,  56.5181],
        [ 84.5952,  84.0923],
        [114.7178, 114.2150],
        [ 20.1613,  19.6584],
        [106.3933, 105.8905]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
