In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [74, 66, 43], [91, 87, 65], [88, 134, 59], [101, 44, 37], [68, 96, 71], [73, 66, 44], [92, 87, 64], 
[87, 135, 57],  [103, 43, 36],   [68, 97, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],  [81, 101],  [119, 133],  [22, 37],  [103, 119], [57, 69],  [80, 102],  [118, 132],  [21, 38],  [104, 118],  [57, 69],  [82, 100],  [118, 134],  [20, 38], [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
inputs
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 91.,  87.,  65.],
        [ 92.,  87.,  64.],
        [ 68.,  96.,  71.],
        [ 88., 134.,  59.]])
tensor([[103., 119.],
        [ 80., 102.],
        [ 82., 100.],
        [104., 118.],
        [118., 132.]])


In [ ]:
# Define model
model = nn.Linear(3, 1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5558, -0.0987,  0.5414]], requires_grad=True)
Parameter containing:
tensor([-0.2805], requires_grad=True)
