# **Task 1: Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%**

In [17]:
import numpy as np
import pandas as pd
# from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder 

from sklearn.naive_bayes import GaussianNB, MultinomialNB

datasets = pd.read_csv('Dataset2.csv')
datasets

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [18]:
print(datasets.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Outlook   14 non-null     object
 1   Temp      14 non-null     object
 2   Wind      14 non-null     object
 3   Humidity  14 non-null     object
 4   Class     14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes
None


In [19]:
x=datasets.iloc[:,:4].values
y=datasets.iloc[:,-1].values

print("INPUTS: \n",x)
print("OUTPUT: \n",y)

INPUTS: 
 [['R' 'H' 'F' 'Normal']
 ['R' 'H' 'T' 'High']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'T' 'Low']
 ['O' 'C' 'T' 'Normal']
 ['R' 'C' 'F' 'Normal']
 ['R' 'C' 'F' 'Low']
 ['S' 'M' 'F' 'High']
 ['R' 'M' 'T' 'High']
 ['O' 'M' 'T' 'Low']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'T' 'Normal']]
OUTPUT: 
 ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [20]:
#Use One Hot Encoder from scikit learn
onehotencoder = OneHotEncoder()

#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object 

feature1=onehotencoder.fit_transform(datasets.Outlook.values.reshape(-1,1)).toarray()
feature2=onehotencoder.fit_transform(datasets.Temp.values.reshape(-1,1)).toarray()
feature3=onehotencoder.fit_transform(datasets.Wind.values.reshape(-1,1)).toarray()
feature4=onehotencoder.fit_transform(datasets.Humidity.values.reshape(-1,1)).toarray()

label = onehotencoder.fit_transform(datasets.Class.values.reshape(-1,1)).toarray()

# print(feature1 ,"\n")
# print(feature2 ,"\n")
# print(feature3 ,"\n")
# print(feature4 ,"\n")
print(label ,"\n")

df1 = pd.DataFrame(feature1, columns=["Outlook_"+str(int(i)) for i in range(len(feature1[0]))])
df2 = pd.DataFrame(feature2, columns=["Temp_"+str(int(i)) for i in range(len(feature2[0]))])
df3 = pd.DataFrame(feature3, columns=["Wind_"+str(int(i)) for i in range(len(feature3[0]))])
df4 = pd.DataFrame(feature4, columns=["Humidity_"+str(int(i)) for i in range(len(feature4[0]))])

label = pd.DataFrame(label, columns=["Class_" + str(int(i)) for i in range(len(label[0]))])

print(label)

df = pd.concat([df1, df2, df3, df4], axis=1)
# print(df)
df


[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]] 

    Class_0  Class_1
0       1.0      0.0
1       1.0      0.0
2       0.0      1.0
3       1.0      0.0
4       0.0      1.0
5       0.0      1.0
6       0.0      1.0
7       0.0      1.0
8       0.0      1.0
9       0.0      1.0
10      0.0      1.0
11      0.0      1.0
12      0.0      1.0
13      1.0      0.0


Outlook_0  Outlook_1  Outlook_2  ...  Humidity_0  Humidity_1  Humidity_2
0         0.0        1.0        0.0  ...         0.0         0.0         1.0
1         0.0        1.0        0.0  ...         1.0         0.0         0.0
2         1.0        0.0        0.0  ...         0.0         0.0         1.0
3         0.0        0.0        1.0  ...         0.0         0.0         1.0
4         0.0        0.0        1.0  ...         0.0         0.0         1.0
5         0.0        0.0        1.0  ...         0.0         1.0         0.0
6         1.0        0.0        0.0  ...         0.0         0.0         1.0
7         0.0        1.0        0.0  ...         0.0         0.0         1.0
8         0.0        1.0        0.0  ...         0.0         1.0         0.0
9         0.0        0.0        1.0  ...         1.0         0.0         0.0
10        0.0        1.0        0.0  ...         1.0         0.0         0.0
11        1.0        0.0        0.0  ...         0.0         1.0         0.0
12        1.0        0.0        0.0  ...         0.0         0.0         1.0
13        0.0        0.0        1.0  ...         0.0         0.0         1.0

[14 rows x 11 columns]

In [21]:
#combine all columns and create one feature

# features = tuple(zip(feature1, feature2, feature3, feature4))

features = df.iloc[:,:].values

print(features)

[[0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]]


###**Use Multinomial Naive Bayes Algo.**

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(df, y, test_size=.20, random_state=0)

print("X_train:-\n", X_train)
print("X_test:-\n", X_test)
print("Y_train:-\n", Y_train)
print("Y_test:-\n", Y_test)

model = MultinomialNB()
model.fit(X_train, Y_train)

predicted= model.predict(X_test)
print("\nPredicted Value:", predicted)

X_train:-
     Outlook_0  Outlook_1  Outlook_2  ...  Humidity_0  Humidity_1  Humidity_2
11        1.0        0.0        0.0  ...         0.0         1.0         0.0
2         1.0        0.0        0.0  ...         0.0         0.0         1.0
13        0.0        0.0        1.0  ...         0.0         0.0         1.0
9         0.0        0.0        1.0  ...         1.0         0.0         0.0
1         0.0        1.0        0.0  ...         1.0         0.0         0.0
7         0.0        1.0        0.0  ...         0.0         0.0         1.0
10        0.0        1.0        0.0  ...         1.0         0.0         0.0
3         0.0        0.0        1.0  ...         0.0         0.0         1.0
0         0.0        1.0        0.0  ...         0.0         0.0         1.0
5         0.0        0.0        1.0  ...         0.0         1.0         0.0
12        1.0        0.0        0.0  ...         0.0         0.0         1.0

[11 rows x 11 columns]
X_test:-
    Outlook_0  Outlook_1  Outloo

# **Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%**

In [23]:
import numpy as numpy
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

wine = datasets.load_wine()

In [24]:
print("Features: ", wine.feature_names)

print("Labels: ", wine.target_names)

print("\nData shape: ", wine.data.shape)

print("\nTarget shape: ", wine.target.shape)

print("\nData type: ", type(wine.data))

newdata = wine.data[: , :]
newtarget = wine.target[:]

print("\nNew Data shape: ", newdata.shape)
print("\nNew Target shape: ", newtarget.shape)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']

Data shape:  (178, 13)

Target shape:  (178,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (178, 13)

New Target shape:  (178,)


In [25]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=10)

In [26]:
print(data_train.shape) #which is 80% of 178
print(data_test.shape) #which is 20% of 178 

(142, 13)
(36, 13)


In [27]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

print(target_pred)

[1 1 0 1 0 1 1 0 2 0 0 0 0 2 1 1 2 1 1 2 0 2 0 0 1 2 1 2 1 1 2 2 2 2 1 0]


**Find Accuracy using metrics**

In [28]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8888888888888888


**Find Confusion Matrix**

In [29]:
from sklearn.metrics import confusion_matrix

confusion_matrix(target_test, target_pred)

array([[10,  0,  0],
       [ 1, 14,  3],
       [ 0,  0,  8]])

**Find Precision Call & Recall**

In [30]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
print('Precison: {}'.format(precision))

recall = recall_score(target_test, target_pred, average=None)
print('Recall: {}'.format(recall))

Precison: [0.90909091 1.         0.72727273]
Recall: [1.         0.77777778 1.        ]
